import Link from "next/link";
import type { Metadata } from "next";
import { SITE_HOST } from "@/lib/site";

const mono = { fontFamily: "var(--font-plex-mono), monospace" };
const display = { fontFamily: "var(--font-fraunces), serif", fontWeight: 600 };

export const metadata: Metadata = {
  title: "Sweep No. 1 — Launch week, mid-crisis",
  description:
    "BTCSCAM's first weekly desk report: the registry opened during the Coldcard seed-entropy crisis with 3 dossiers, 1 public correction, 2 new guides, 120 wire drafts awaiting triage, and 0 reader reports.",
  alternates: { canonical: "/sweep/2026-08-11" },
};

function SectionRule({ label, danger }: { label: string; danger?: boolean }) {
  return (
    <h2
      style={{
        ...mono,
        fontSize: 12,
        fontWeight: 600,
        letterSpacing: ".05em",
        color: danger ? "var(--danger)" : "var(--ink)",
        borderBottom: "2px solid var(--ink)",
        paddingBottom: 8,
        marginTop: 40,
      }}
    >
      {label}
    </h2>
  );
}

function Stat({ n, label }: { n: string; label: string }) {
  return (
    <div>
      <div style={{ ...mono, fontSize: 22, fontWeight: 600 }}>{n}</div>
      <div style={{ ...mono, fontSize: 11, color: "var(--meta)", letterSpacing: ".05em" }}>
        {label}
      </div>
    </div>
  );
}

export default function SweepOne() {
  return (
    <main style={{ maxWidth: 780, margin: "0 auto", padding: "0 24px 64px" }}>
      <nav style={{ ...mono, fontSize: 12, padding: "16px 0" }}>
        <Link href="/">← FRONT PAGE</Link>
        <span style={{ color: "var(--meta)" }}> / </span>
        <Link href="/sweep">THE MONDAY SWEEP</Link>
        <span style={{ color: "var(--meta)" }}> / NO. 1</span>
      </nav>

      <p style={{ ...mono, fontSize: 12, fontWeight: 600, letterSpacing: ".05em", color: "var(--meta)", margin: 0 }}>
        THE MONDAY SWEEP · NO. 1 · WEEK OF 2026-08-04 → 2026-08-11
      </p>
      <h1 style={{ ...display, fontSize: "clamp(28px, 5vw, 40px)", lineHeight: 1.15, margin: "8px 0 0" }}>
        Launch week, mid-crisis
      </h1>
      <p style={{ fontSize: 18, lineHeight: 1.55, marginTop: 16 }}>
        BTCSCAM opened its doors in the middle of the biggest hardware-wallet
        theft on record. This is the desk&apos;s first weekly report — the week
        as it actually was, small numbers printed as small numbers.
      </p>

      <div
        style={{
          display: "flex",
          gap: 32,
          background: "var(--panel)",
          padding: "16px 20px",
          marginTop: 20,
          flexWrap: "wrap",
        }}
      >
        <Stat n="3" label="DOSSIERS ON THE RECORD" />
        <Stat n="1" label="PUBLIC CORRECTION" />
        <Stat n="3" label="GUIDES LIVE" />
        <Stat n="120" label="WIRE DRAFTS QUEUED" />
        <Stat n="0" label="READER REPORTS" />
      </div>

      <SectionRule label="ON THE RECORD" danger />
      <p style={{ fontSize: 16, lineHeight: 1.6, marginTop: 16 }}>
        The registry opened 2026-08-08 with three dossiers. The lead story is
        the{" "}
        <Link href="/scam/coldcard-rng-seed-entropy-flaw-2026" style={{ fontWeight: 700 }}>
          Coldcard seed-entropy flaw
        </Link>{" "}
        — $116M–$130M+ swept from wallets whose seeds were generated by a
        silently broken RNG (the range is deliberate; see Corrections). Riding
        in its wake, the{" "}
        <Link href="/scam/coldcard-hardware-audit-phishing-2026" style={{ fontWeight: 700 }}>
          &quot;hardware audit&quot; phishing wave
        </Link>{" "}
        — fake Coinkite emails installing remote-access software on the
        machines of already-frightened owners. The third,{" "}
        <Link href="/scam/milk-sad-libbitcoin-explorer-weak-entropy" style={{ fontWeight: 700 }}>
          Milk Sad
        </Link>{" "}
        (2023), is the historical backfill that proves the entropy failure
        pattern predates this month.
      </p>

      <SectionRule label="CORRECTIONS — WE ARE WRONG OUT LOUD" />
      <p style={{ fontSize: 16, lineHeight: 1.6, marginTop: 16 }}>
        One correction this week, logged 2026-08-11 on the Coldcard dossier:
        our launch headline read &quot;~$116M+&quot; sourced to TRM Labs as of
        Aug 5. That figure held, but aggregate reporting moved — 2,000+ BTC
        logged by Aug 10, $130M+ per TechCrunch and Decrypt — and Coinkite
        itself declines to estimate. The headline now carries the dated range,
        and the correction is{" "}
        <Link href="/scam/coldcard-rng-seed-entropy-flaw-2026" style={{ fontWeight: 700 }}>
          permanent on the dossier
        </Link>
        . Corrections rate, week one: 1 correction on 3 published dossiers.
        High. It stays public anyway — that is the whole point of the ledger.
      </p>

      <SectionRule label="NEW GUIDES" />
      <p style={{ fontSize: 16, lineHeight: 1.6, marginTop: 16 }}>
        Two guides shipped 2026-08-11 as a pair, aimed at the panic window the
        Coldcard wave created:{" "}
        <Link href="/guides/wallet-phishing-recognition" style={{ fontWeight: 700 }}>
          how to recognize wallet-company phishing
        </Link>{" "}
        (a real Coinkite email and a fake audit circulated the same week — the
        domain and the ask are the only tells that matter) and{" "}
        <Link href="/guides/hardware-wallet-authenticity" style={{ fontWeight: 700 }}>
          how to verify a hardware wallet is genuine
        </Link>{" "}
        (the pre-filled recovery card is the kill pattern). They join the{" "}
        <Link href="/guides/seed-phrase-entropy" style={{ fontWeight: 700 }}>
          seed-entropy guide
        </Link>{" "}
        from launch.
      </p>

      <SectionRule label="THE WIRE" />
      <p style={{ fontSize: 16, lineHeight: 1.6, marginTop: 16 }}>
        The ingest pipeline&apos;s first runs queued 120 draft leads for human
        triage (as of 2026-08-11): 108 from DeFiLlama&apos;s historical hacks
        backfill, 10 from Bitcoin Optech, 2 from FTC consumer alerts. None of
        them publish themselves — nothing on this site auto-publishes above
        REPORTED. The blacklist mirror behind{" "}
        <Link href="/check" style={{ fontWeight: 700 }}>
          /check
        </Link>{" "}
        held 2,530 flagged addresses and 449,804 flagged domains as of
        2026-08-10 (ScamSniffer + MetaMask eth-phishing-detect, credited on the
        check desk). In editorial review behind the scenes: 12 seed dossiers
        drafted from federal and first-party sources — Bitcoin ATM shakedowns,
        the recovery-scam industry, the Ledger and Trezor impersonation
        ecosystems, and the canonical historical frauds. They publish only
        after human review, dated as they land.
      </p>

      <SectionRule label="READER REPORTS" />
      <p style={{ fontSize: 16, lineHeight: 1.6, marginTop: 16 }}>
        Zero reports received in week one. That is the honest number, printed
        per the constitution — no fake member counts, no seeded activity. The{" "}
        <Link href="/report" style={{ fontWeight: 700 }}>
          report desk
        </Link>{" "}
        is open, a human reads every submission, and every report gets a
        visible status on the{" "}
        <Link href="/reports/open" style={{ fontWeight: 700 }}>
          open ledger
        </Link>{" "}
        — no black holes here.
      </p>

      <SectionRule label="CLONE WATCH" />
      <p style={{ fontSize: 16, lineHeight: 1.6, marginTop: 16 }}>
        First brand-impersonation sweep ran 2026-08-11: no certificates issued
        for lookalike names, no active clone of this site found. For the
        record: {SITE_HOST} is our only domain. Anything else wearing this name
        is an impostor — check your address bar.
      </p>

      <p style={{ ...mono, fontSize: 12, color: "var(--meta)", letterSpacing: ".05em", marginTop: 40, borderTop: "1px solid var(--rule)", paddingTop: 16 }}>
        NEXT SWEEP: MONDAY 2026-08-18 · NUMBERS AS OF DATES SHOWN · FOUND AN
        ERROR? <Link href="/report">REPORT IT</Link> — WE CORRECT IN PUBLIC.
      </p>
    </main>
  );
}
